"""Voice Pipeline Subsystem for J.A.R.V.I.S.

Provides the end-to-end voice orchestration layer integrating audio input,
Speech-to-Text (STT), wake word detection, command routing, conversational memory,
and Text-to-Speech (TTS) response synthesis within an async-ready state machine.
"""

from __future__ import annotations

from app.voice.engine import (
    EVENT_ENGINE_COMPLETED,
    EVENT_ENGINE_FAILED,
    EVENT_ENGINE_RECORDING,
    EVENT_ENGINE_ROUTING,
    EVENT_ENGINE_SPEAKING,
    EVENT_ENGINE_STARTED,
    EVENT_ENGINE_STOPPED,
    EVENT_ENGINE_TRANSCRIBING,
    EVENT_SOURCE_VOICE_ENGINE,
    VoiceConversationEngine,
    voice_conversation_engine,
)
from app.voice.microphone import (
    DEFAULT_CHANNELS,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_RECORD_DURATION,
    DEFAULT_SAMPLE_RATE,
    DEFAULT_SAMPLE_WIDTH,
    EVENT_MICROPHONE_RECORDED,
    EVENT_MICROPHONE_RECORDING,
    EVENT_MICROPHONE_STARTED,
    EVENT_MICROPHONE_STOPPED,
    EVENT_SOURCE_MICROPHONE,
    MicrophoneRecorder,
    microphone,
    microphone_recorder,
)
from app.voice.models import (
    AudioProvider,
    AudioProviderError,
    InvalidStateError,
    MicrophoneError,
    PlaceholderAudioProvider,
    PipelineExecutionError,
    PipelineNotRunningError,
    RecordingError,
    VoiceConversationResult,
    VoicePipelineError,
    VoicePipelineResult,
    VoiceState,
)
from app.voice.pipeline import (
    EVENT_SOURCE_VOICE,
    EVENT_VOICE_FAILED,
    EVENT_VOICE_LISTENING,
    EVENT_VOICE_PROCESSING,
    EVENT_VOICE_RESPONDING,
    EVENT_VOICE_STARTED,
    EVENT_VOICE_STOPPED,
    VoicePipeline,
    voice_pipeline,
)

__all__ = [
    "AudioProvider",
    "AudioProviderError",
    "DEFAULT_CHANNELS",
    "DEFAULT_CHUNK_SIZE",
    "DEFAULT_RECORD_DURATION",
    "DEFAULT_SAMPLE_RATE",
    "DEFAULT_SAMPLE_WIDTH",
    "EVENT_ENGINE_COMPLETED",
    "EVENT_ENGINE_FAILED",
    "EVENT_ENGINE_RECORDING",
    "EVENT_ENGINE_ROUTING",
    "EVENT_ENGINE_SPEAKING",
    "EVENT_ENGINE_STARTED",
    "EVENT_ENGINE_STOPPED",
    "EVENT_ENGINE_TRANSCRIBING",
    "EVENT_MICROPHONE_RECORDED",
    "EVENT_MICROPHONE_RECORDING",
    "EVENT_MICROPHONE_STARTED",
    "EVENT_MICROPHONE_STOPPED",
    "EVENT_SOURCE_MICROPHONE",
    "EVENT_SOURCE_VOICE",
    "EVENT_SOURCE_VOICE_ENGINE",
    "EVENT_VOICE_FAILED",
    "EVENT_VOICE_LISTENING",
    "EVENT_VOICE_PROCESSING",
    "EVENT_VOICE_RESPONDING",
    "EVENT_VOICE_STARTED",
    "EVENT_VOICE_STOPPED",
    "InvalidStateError",
    "MicrophoneError",
    "MicrophoneRecorder",
    "PlaceholderAudioProvider",
    "PipelineExecutionError",
    "PipelineNotRunningError",
    "RecordingError",
    "VoiceConversationEngine",
    "VoiceConversationResult",
    "VoicePipeline",
    "VoicePipelineError",
    "VoicePipelineResult",
    "VoiceState",
    "microphone",
    "microphone_recorder",
    "voice_conversation_engine",
    "voice_pipeline",
]
