"""Episodic Swarm Memory for Phase 19.2.

Provides thread-safe storage, inverted token indexing, deterministic similarity retrieval,
and agent affinity boosting based on past swarm execution trajectories.
"""

from __future__ import annotations

import logging
import re
import threading
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set, Tuple

from app.ai.planner.swarm.experience import ExperienceSynthesizer

logger = logging.getLogger("app.ai.planner.swarm.episodic")

_WORD_PATTERN = re.compile(r"\w+")


def _tokenize(text: str) -> Set[str]:
    """Extract normalized alphanumeric tokens from text."""
    return set(_WORD_PATTERN.findall(text.lower()))


def _compute_jaccard(tokens_a: Set[str], tokens_b: Set[str]) -> float:
    """Compute Jaccard similarity score between two token sets."""
    if not tokens_a or not tokens_b:
        return 0.0
    intersection = len(tokens_a & tokens_b)
    union = len(tokens_a | tokens_b)
    return intersection / union if union > 0 else 0.0


@dataclass
class TrajectoryRecord:
    """Immutable record capturing an executed plan trajectory and its outcome.

    Attributes:
        trajectory_id: Unique identifier for the execution trajectory.
        goal: Original user goal or mission prompt.
        plan_signature: Structural signature of the plan/DAG executed.
        success: Whether the execution succeeded end-to-end.
        total_duration_ms: Total elapsed execution time in milliseconds.
        timestamp: Unix epoch timestamp when trajectory occurred.
        agent_ratings: Performance ratings (0.0 - 1.0) awarded to participating agents.
        recovery_events: Log of recovery heuristics or replans triggered during execution.
        artifacts_produced: Identifiers of artifacts generated by the trajectory.
    """

    trajectory_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    goal: str = ""
    plan_signature: str = ""
    success: bool = True
    total_duration_ms: float = 0.0
    timestamp: float = field(default_factory=time.time)
    agent_ratings: Dict[str, float] = field(default_factory=dict)
    recovery_events: List[Dict[str, Any]] = field(default_factory=list)
    artifacts_produced: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize trajectory record to a dictionary."""
        return {
            "trajectory_id": self.trajectory_id,
            "goal": self.goal,
            "plan_signature": self.plan_signature,
            "success": self.success,
            "total_duration_ms": self.total_duration_ms,
            "timestamp": self.timestamp,
            "agent_ratings": dict(self.agent_ratings),
            "recovery_events": [dict(e) for e in self.recovery_events],
            "artifacts_produced": list(self.artifacts_produced),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> TrajectoryRecord:
        """Deserialize trajectory record from a dictionary."""
        return cls(
            trajectory_id=data.get("trajectory_id", str(uuid.uuid4())),
            goal=data.get("goal", ""),
            plan_signature=data.get("plan_signature", ""),
            success=bool(data.get("success", True)),
            total_duration_ms=float(data.get("total_duration_ms", 0.0)),
            timestamp=float(data.get("timestamp", time.time())),
            agent_ratings=dict(data.get("agent_ratings", {})),
            recovery_events=[dict(e) for e in data.get("recovery_events", [])],
            artifacts_produced=list(data.get("artifacts_produced", [])),
        )


class EpisodicMemoryStore:
    """Thread-safe store indexing execution trajectories and computing agent affinity."""

    def __init__(
        self,
        synthesizer: Optional[ExperienceSynthesizer] = None,
        max_records: int = 10000,
    ) -> None:
        """Initialize EpisodicMemoryStore.

        Args:
            synthesizer: Optional ExperienceSynthesizer for automated metric aggregation.
            max_records: Maximum capacity before pruning oldest entries.
        """
        self._lock = threading.RLock()
        self._synthesizer = synthesizer
        self._max_records = max_records
        self._records: Dict[str, TrajectoryRecord] = {}
        # Inverted index: token -> set of trajectory_ids
        self._inverted_tokens: Dict[str, Set[str]] = {}
        # Agent action affinity: agent_id -> action -> list of ratings
        self._agent_affinities: Dict[str, Dict[str, List[float]]] = {}

    def record_trajectory(self, record: TrajectoryRecord) -> None:
        """Store a trajectory record, update indexes, and trigger synthesizer update.

        Args:
            record: TrajectoryRecord to persist and index.
        """
        with self._lock:
            # Capacity check: prune oldest if limit reached
            if len(self._records) >= self._max_records:
                oldest_id = min(
                    self._records.keys(), key=lambda tid: self._records[tid].timestamp
                )
                self._delete_record(oldest_id)

            self._records[record.trajectory_id] = record

            # Index tokens for fast inverted lookup
            tokens = _tokenize(record.goal)
            for token in tokens:
                if token not in self._inverted_tokens:
                    self._inverted_tokens[token] = set()
                self._inverted_tokens[token].add(record.trajectory_id)

            # Update agent action affinities from ratings and recovery events
            for agent_id, rating in record.agent_ratings.items():
                if agent_id not in self._agent_affinities:
                    self._agent_affinities[agent_id] = {}
                # Record default action rating
                default_action = "*"
                if default_action not in self._agent_affinities[agent_id]:
                    self._agent_affinities[agent_id][default_action] = []
                self._agent_affinities[agent_id][default_action].append(float(rating))

            # If action-specific ratings were recorded in recovery_events or plan_signature
            for ev in record.recovery_events:
                action = ev.get("action")
                agent = ev.get("agent_id")
                score = ev.get("score")
                if action and agent and score is not None:
                    if agent not in self._agent_affinities:
                        self._agent_affinities[agent] = {}
                    if action not in self._agent_affinities[agent]:
                        self._agent_affinities[agent][action] = []
                    self._agent_affinities[agent][action].append(float(score))

            # Update experience synthesizer if provided
            if self._synthesizer is not None:
                self._synthesizer.update_from_record(record)

    def _delete_record(self, trajectory_id: str) -> None:
        """Internal helper to remove a record and clean up index entries."""
        record = self._records.pop(trajectory_id, None)
        if record is None:
            return

        tokens = _tokenize(record.goal)
        for token in tokens:
            if token in self._inverted_tokens:
                self._inverted_tokens[token].discard(trajectory_id)
                if not self._inverted_tokens[token]:
                    del self._inverted_tokens[token]

    def query_similar_goals(
        self,
        goal: str,
        top_k: int = 3,
        threshold: float = 0.0,
    ) -> List[TrajectoryRecord]:
        """Query similar past trajectories using token Jaccard similarity.

        Args:
            goal: Query goal string.
            top_k: Maximum number of matches to return.
            threshold: Minimum similarity score threshold (0.0 - 1.0).

        Returns:
            List of matching TrajectoryRecords sorted by relevance.
        """
        with self._lock:
            query_tokens = _tokenize(goal)
            if not query_tokens:
                return []

            # Find candidate trajectory IDs from inverted token index
            candidate_ids: Set[str] = set()
            for token in query_tokens:
                if token in self._inverted_tokens:
                    candidate_ids.update(self._inverted_tokens[token])

            if not candidate_ids:
                return []

            # Score candidates deterministically
            scored_candidates: List[Tuple[float, float, str, TrajectoryRecord]] = []
            for tid in candidate_ids:
                rec = self._records[tid]
                rec_tokens = _tokenize(rec.goal)
                score = _compute_jaccard(query_tokens, rec_tokens)

                # Bonus for exact goal string match
                if rec.goal.strip().lower() == goal.strip().lower():
                    score = 1.0

                if score >= threshold:
                    # Sort key: (-score, -timestamp, trajectory_id)
                    scored_candidates.append((-score, -rec.timestamp, rec.trajectory_id, rec))

            scored_candidates.sort()
            return [item[3] for item in scored_candidates[:top_k]]

    def get_agent_affinity_boost(self, agent_id: str, action: str) -> float:
        """Calculate historical affinity boost score for an agent on a specific action.

        Args:
            agent_id: Target agent identifier.
            action: Specific action or generic task type.

        Returns:
            Non-negative affinity multiplier boost (e.g. 0.0 to 0.35).
        """
        with self._lock:
            agent_map = self._agent_affinities.get(agent_id)
            if not agent_map:
                return 0.0

            # Prefer action-specific ratings, fallback to wildcard '*' ratings
            scores = agent_map.get(action) or agent_map.get("*")
            if not scores:
                return 0.0

            avg_rating = sum(scores) / len(scores)
            # Baseline is 0.5; ratings above baseline grant a positive boost up to 0.35
            if avg_rating > 0.5:
                boost = (avg_rating - 0.5) * 0.7
                return round(min(0.35, max(0.0, boost)), 4)
            return 0.0

    def export_knowledge(self) -> Dict[str, Any]:
        """Export serialized knowledge snapshot for backup or distribution.

        Returns:
            Dictionary containing serialized records, agent affinities, and stats.
        """
        with self._lock:
            return {
                "record_count": len(self._records),
                "records": [rec.to_dict() for rec in self._records.values()],
                "agent_affinities": {
                    agent: {act: list(scores) for act, scores in acts.items()}
                    for agent, acts in self._agent_affinities.items()
                },
                "indexed_tokens_count": len(self._inverted_tokens),
            }

    def import_knowledge(self, data: Dict[str, Any]) -> None:
        """Restore knowledge store from exported dictionary.

        Args:
            data: Exported dictionary from export_knowledge().
        """
        with self._lock:
            for rec_dict in data.get("records", []):
                rec = TrajectoryRecord.from_dict(rec_dict)
                self.record_trajectory(rec)
