"""Vision and Screen Intelligence Package for J.A.R.V.I.S. Phase 27.

Provides native Windows desktop screen capture, multi-monitor topology inspection,
active-window tracking, and typed in-memory capture models.
"""

from __future__ import annotations

from app.vision.capture import (
    CaptureBackend,
    DesktopCaptureEngine,
    MockCaptureBackend,
    Win32GdiCaptureBackend,
    init_dpi_awareness,
)
from app.vision.models import (
    BufferExpiredError,
    CaptureAuthorization,
    CaptureBlockedError,
    CaptureCategory,
    CaptureDecision,
    CaptureError,
    GdiResourceError,
    InvalidBoundsError,
    MonitorInfo,
    OCRResult,
    OCRTextBlock,
    Point,
    ScreenCapture,
    ScreenObservation,
    UnsupportedPlatformError,
    VisionError,
    VisionSecurityError,
    VisualAnalysisResult,
    VisualDeltaResult,
    VisualDeltaType,
    VisualElementTrack,
    VisualEventType,
    VisualEvidenceItem,
    VisualGoalCriterion,
    VisualGoalSpec,
    VisualGroundingResult,
    VisualOutcomeType,
    VisualSituation,
    VisualSituationResult,
    VisualSituationType,
    VisualTemporalEvent,
    VisualTemporalHistoryResult,
    VisualTrackStatus,
    VisualTrackingResult,
    VisualVerificationResult,
    WindowBounds,
)
from app.vision.ocr import (
    MockOCRProvider,
    MultimodalVisionOCRAdapter,
    OCRProvider,
    WindowsMediaOCRProvider,
)
from app.vision.preprocessing import (
    ImagePreprocessor,
    capture_to_image_part,
    default_preprocessor,
    preprocess_capture,
)
from app.vision.security import (
    EphemeralBufferManager,
    SecureVisionManager,
    SensitiveWindowRule,
    VisionSecurityPolicy,
)
from app.vision.situation import (
    VisualSituationEngine,
)
from app.vision.temporal import (
    VisualTemporalEngine,
    VisualTemporalLog,
)
from app.vision.tracking import (
    VisualTrackingEngine,
)
from app.vision.verification import (
    VisualVerificationEngine,
    parse_visual_goal,
)

__all__ = [
    "BufferExpiredError",
    "CaptureAuthorization",
    "CaptureBackend",
    "CaptureBlockedError",
    "CaptureCategory",
    "CaptureDecision",
    "CaptureError",
    "DesktopCaptureEngine",
    "EphemeralBufferManager",
    "GdiResourceError",
    "ImagePreprocessor",
    "InvalidBoundsError",
    "MockCaptureBackend",
    "MockOCRProvider",
    "MonitorInfo",
    "MultimodalVisionOCRAdapter",
    "OCRProvider",
    "OCRResult",
    "OCRTextBlock",
    "Point",
    "ScreenCapture",
    "ScreenObservation",
    "SecureVisionManager",
    "SensitiveWindowRule",
    "UnsupportedPlatformError",
    "VisionError",
    "VisionSecurityError",
    "VisionSecurityPolicy",
    "VisualAnalysisResult",
    "VisualDeltaResult",
    "VisualDeltaType",
    "VisualElementTrack",
    "VisualEventType",
    "VisualEvidenceItem",
    "VisualGoalCriterion",
    "VisualGoalSpec",
    "VisualGroundingResult",
    "VisualOutcomeType",
    "VisualSituation",
    "VisualSituationEngine",
    "VisualSituationResult",
    "VisualSituationType",
    "VisualTemporalEngine",
    "VisualTemporalEvent",
    "VisualTemporalHistoryResult",
    "VisualTemporalLog",
    "VisualTrackStatus",
    "VisualTrackingEngine",
    "VisualTrackingResult",
    "VisualVerificationEngine",
    "VisualVerificationResult",
    "Win32GdiCaptureBackend",
    "WindowBounds",
    "WindowsMediaOCRProvider",
    "capture_to_image_part",
    "default_preprocessor",
    "init_dpi_awareness",
    "parse_visual_goal",
    "preprocess_capture",
]
